FROM akkerman/rpi-nginx:wheezy

LABEL maintainer "ikbenMarcelAkkerman@hotmail.com"
add www /usr/share/nginx/www

# docker build -t my-nginx-image .
# docker run -p 80:80 --name my-nginx-container -d my-nginx-image 
